
spring:
  application:
    name: ProductService
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/product_db

    # Kullanıcı Adı (Docker Compose'daki POSTGRES_USER)
    username: admin

    # Şifre (Docker Compose'daki POSTGRES_PASSWORD)
    password: admin

    # Sürücü Sınıfı
    driver-class-name: org.postgresql.Driver

    # ----------------------------------------
    # JPA ve Hibernate Ayarları (Opsiyonel)
    # ----------------------------------------
  kafka:
    producer:
      # Kafka Broker Adresleri (Genellikle localhost:9092)
      bootstrap-servers: localhost:9092

      topic-name: "product_created_event"
      update-product-topic-name: "product_updated_event"

      # Key Serializer: Mesaj anahtarını bayt dizisine çevirir
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      # Value Serializer: Mesaj değerini bayt dizisine çevirir (String veya JSON için)
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8089